<?php
ob_start();require dirname(__DIR__).'/wp-runtime-probe.php';ob_end_clean();
$_COOKIE=[];
$banner=Marrison_Cookie_Banner::get_instance();
ob_start();$banner->render_banner();$banner->render_floating_widget();$ui=ob_get_clean();
$plugin='/wp-content/plugins/marrison-addon/includes/modules/cookie-manager/';
$html='<!doctype html><html><head><meta charset="utf-8"><title>Cookie fixes audit</title><link rel="stylesheet" href="'.$plugin.'assets/css/frontend.css"><style>body{font:18px Arial;margin:20px}button{padding:8px;margin:4px}iframe{height:80px;width:45%}h3{color:#fff}output{display:block;padding:5px}</style></head><body><h1>Cookie blocking and module activation</h1><button id="none">No consent</button><button id="analytics">Grant Analytics</button><button id="all">Grant All</button><button id="restore">Restore original consent</button><output id="phase"></output><output id="analytics-state">analytics: 0</output><output id="module-state">module: 0</output><output id="unquoted-module-state">unquoted module: 0</output><output id="marketing-state">marketing: 0</output><h2>Quoted / unquoted iframe</h2><iframe id="quoted" src="/marrison-remediation-youtube.com.html"></iframe><iframe id="unquoted" src=/marrison-remediation-youtube.com.html></iframe>';
$html.='<script>/* gtag( marker */document.getElementById("analytics-state").textContent="analytics: 1";</script><script type="module" id="module">/* gtag( marker */export const marker=true;document.getElementById("module-state").textContent="module: 1";</script><script type=module id="unquoted-module">/* gtag( marker */export const marker=true;document.getElementById("unquoted-module-state").textContent="unquoted module: 1";</script><script>/* fbq( marker */document.getElementById("marketing-state").textContent="marketing: 1";</script>';
$html.=$ui.'<script src="/wp-includes/js/jquery/jquery.min.js"></script><script>var marrisonCookie={ajaxUrl:"/wp-admin/admin-ajax.php",nonce:"fixture-not-used",consentDuration:30,customizeTitle:"Personalizza Cookie",acceptAll:"Accetta tutti",rejectAll:"Rifiuta tutti",savePreferences:"Salva Preferenze",hasConsent:false,closedTriggerModes:{desktop:"floating",tablet:"floating",mobile:"floating"}};var consentNames=["marrison_cookie_consent","marrison_cookie_categories"];var storageKey="marrison-remediation-original-consent";if(!sessionStorage.getItem(storageKey)){var original={};consentNames.forEach(function(name){var match=document.cookie.match(new RegExp("(?:^|; )"+name+"=([^;]*)"));original[name]=match?match[1]:null;document.cookie=name+"=;Max-Age=0;path=/";});sessionStorage.setItem(storageKey,JSON.stringify(original));sessionStorage.setItem("marrison-remediation-phase","none");}document.getElementById("phase").textContent="Phase: "+sessionStorage.getItem("marrison-remediation-phase");function phase(mode){consentNames.forEach(function(name){document.cookie=name+"=;Max-Age=0;path=/";});if(mode!=="none"){document.cookie="marrison_cookie_consent="+(mode==="all"?"accept_all":"custom")+";path=/;SameSite=Lax";document.cookie="marrison_cookie_categories=necessary%7Canalytics"+(mode==="all"?"%7Cmarketing%7Cfunctional":"")+";path=/;SameSite=Lax";}sessionStorage.setItem("marrison-remediation-phase",mode);location.reload();}["none","analytics","all"].forEach(function(mode){document.getElementById(mode).onclick=function(){phase(mode);};});document.getElementById("restore").onclick=function(){var original=JSON.parse(sessionStorage.getItem(storageKey));consentNames.forEach(function(name){document.cookie=name+"=;Max-Age=0;path=/";if(original[name]!==null){document.cookie=name+"="+original[name]+";path=/;SameSite=Lax";}});sessionStorage.removeItem(storageKey);sessionStorage.removeItem("marrison-remediation-phase");document.getElementById("phase").textContent="Original consent restored";document.getElementById("restore").disabled=true;};</script><script src="'.$plugin.'assets/js/frontend.js"></script></body></html>';
$filtered=Marrison_Cookie_Consent::get_instance()->filter_output($html);
file_put_contents(__DIR__.'/cookie.html',$filtered);
file_put_contents(__DIR__.'/youtube.com.html','<!doctype html><html><head><title>Local iframe</title></head><body>Local test iframe loaded</body></html>');
$checks=['quoted_src_removed'=>strpos($filtered,' id="quoted" src=')===false,'unquoted_src_removed'=>strpos($filtered,' id="unquoted" src=')===false,'module_type_saved'=>substr_count($filtered,'data-marrison-script-type="module"')===2,'errors'=>$GLOBALS['audit_errors']];
file_put_contents(__DIR__.'/cookie-filter-results.json',wp_json_encode($checks,JSON_PRETTY_PRINT));
echo wp_json_encode($checks)."\n";
